import { useMemo, useState } from "react";
import { BarChart3, BriefcaseBusiness, History, LayoutDashboard, Search, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { AccountHeader } from "./components/AccountHeader";
import { MarketTabs } from "./components/MarketTabs";
import { MarketFinder } from "./components/MarketFinder";
import { ChartWorkspace } from "./components/ChartWorkspace";
import { TradeDeck } from "./components/TradeDeck";
import { DigitDistribution } from "./components/DigitDistribution";
import { SentinelIntelligence } from "./components/SentinelIntelligence";
import { OpenContracts } from "./components/OpenContracts";
import { TradeHistory } from "./components/TradeHistory";
import { marketDataService, openContracts, tradeHistory } from "./services/mockTradingServices";
import { useMarketStream } from "./hooks/useMarketStream";
import type { Market } from "./types";

export function TradingApp() {
 const allMarkets=marketDataService.getMarkets(); const [activeId,setActiveId]=useState("R_50"); const [openIds,setOpenIds]=useState(["R_50","R_75","BOOM500","STP"]); const [finderCollapsed,setFinderCollapsed]=useState(false); const [windowSize,setWindowSize]=useState(120); const [intelOpen,setIntelOpen]=useState(true); const [pressureOpen,setPressureOpen]=useState(false); const [contractsOpen,setContractsOpen]=useState(true); const [view,setView]=useState<"workspace"|"history">("workspace");
 const activeMarket=allMarkets.find(m=>m.id===activeId) ?? allMarkets[0]; const stream=useMarketStream(activeMarket,windowSize); const openMarkets=useMemo(()=>openIds.map(id=>allMarkets.find(m=>m.id===id)).filter((m):m is Market=>Boolean(m)),[openIds,allMarkets]); const prices=Object.fromEntries(allMarkets.map(m=>[m.id,m.id===activeId&&stream.current?stream.current.quote:m.basePrice]));
 const selectMarket=(market:Market)=>{ if(!openIds.includes(market.id)) setOpenIds(ids=>[...ids,market.id]); setActiveId(market.id); };
 const closeMarket=(id:string)=>{ const next=openIds.filter(x=>x!==id); if(!next.length)return; setOpenIds(next); if(id===activeId)setActiveId(next[0]); };
 if(!activeMarket) return null;
 return <div className="flex h-dvh min-h-[680px] flex-col overflow-hidden bg-background text-foreground"><AccountHeader view={view} onView={setView}/><MarketTabs markets={openMarkets} activeId={activeId} prices={prices} onSelect={setActiveId} onClose={closeMarket} onAdd={()=>setFinderCollapsed(false)}/>{view==="history"?<TradeHistory trades={tradeHistory}/>:<div className="flex min-h-0 flex-1"><MarketFinder markets={allMarkets} collapsed={finderCollapsed} onToggle={()=>setFinderCollapsed(v=>!v)} onSelect={selectMarket}/><main className="min-w-0 flex-1 overflow-y-auto"><div className="grid min-h-[430px] lg:grid-cols-[minmax(0,1fr)_310px]"><ChartWorkspace market={activeMarket} ticks={stream.ticks} change={stream.change}/><div className="hidden border-l border-border lg:block"><TradeDeck market={activeMarket}/></div></div><DigitDistribution stats={stream.stats} windowSize={windowSize} onWindow={setWindowSize} recentDigit={stream.current?.digit ?? 0} sentinel={stream.sentinel} pressureOpen={pressureOpen} onPressure={()=>setPressureOpen(v=>!v)}/><SentinelIntelligence state={stream.sentinel} open={intelOpen} onToggle={()=>setIntelOpen(v=>!v)}/><OpenContracts contracts={openContracts} open={contractsOpen} onToggle={()=>setContractsOpen(v=>!v)}/></main></div>}<MobileBar view={view} onView={setView} market={activeMarket} markets={allMarkets} onMarket={selectMarket}/></div>;
}
function MobileBar({view,onView,market,markets,onMarket}:{view:"workspace"|"history";onView:(v:"workspace"|"history")=>void;market:Market;markets:Market[];onMarket:(m:Market)=>void}){return <div className="grid grid-cols-4 border-t border-border bg-panel pb-[env(safe-area-inset-bottom)] lg:hidden"><Button variant="ghost" className="h-14 flex-col rounded-none text-[10px]" onClick={()=>onView("workspace")}><LayoutDashboard/>Workspace</Button><Sheet><SheetTrigger asChild><Button variant="ghost" className="h-14 flex-col rounded-none text-[10px]"><Search/>Markets</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[78vh] overflow-auto p-0"><SheetHeader className="border-b border-border p-4 text-left"><SheetTitle>Derived markets</SheetTitle></SheetHeader><div className="grid grid-cols-2 gap-px bg-border">{markets.map(m=><button key={m.id} onClick={()=>onMarket(m)} className="bg-panel p-4 text-left"><div className="text-xs font-semibold">{m.name}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{m.basePrice.toFixed(m.decimals)}</div></button>)}</div></SheetContent></Sheet><Sheet><SheetTrigger asChild><Button variant="default" className="h-14 flex-col rounded-none text-[10px]"><TrendingUp/>Trade</Button></SheetTrigger><SheetContent side="bottom" className="h-[88vh] overflow-auto p-0"><SheetHeader className="sr-only"><SheetTitle>Trade Deck</SheetTitle></SheetHeader><TradeDeck market={market}/></SheetContent></Sheet><Sheet><SheetTrigger asChild><Button variant="ghost" className="h-14 flex-col rounded-none text-[10px]"><BriefcaseBusiness/>Contracts</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[70vh] overflow-auto p-0"><SheetHeader className="border-b border-border p-4 text-left"><SheetTitle>Open contracts</SheetTitle></SheetHeader><OpenContracts contracts={openContracts} open onToggle={()=>{}}/></SheetContent></Sheet>{view==="history"&&<button className="absolute bottom-16 right-3 flex items-center gap-1 border border-border bg-panel p-2 text-xs" onClick={()=>onView("workspace")}><BarChart3 className="size-3"/>Return to workspace</button>}<button aria-label="Open history" onClick={()=>onView("history")} className="sr-only"><History/></button></div>}
