import { ChevronDown, ChevronUp, Minus, TrendingDown, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { DigitStat, SentinelState } from "../types";

const windows = [20,50,100,120,500,1000];
export function DigitDistribution({ stats, windowSize, onWindow, recentDigit, sentinel, pressureOpen, onPressure }: { stats: DigitStat[]; windowSize: number; onWindow: (value:number) => void; recentDigit: number; sentinel: SentinelState; pressureOpen: boolean; onPressure: () => void }) {
 const even = stats.filter(s => s.digit%2===0).reduce((a,s)=>a+s.percentage,0); const sorted=[...stats].sort((a,b)=>b.percentage-a.percentage); const streakDigit=recentDigit;
 return <section className="border-t border-border bg-panel"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-3 py-2"><div><div className="label">Live digit distribution</div><div className="mt-0.5 text-[10px] text-muted-foreground">Authoritative tick sample · {windowSize} ticks</div></div><div className="segmented">{windows.map((item)=><button key={item} className={item===windowSize?"active":""} onClick={()=>onWindow(item)}>{item}</button>)}</div></div><div className="grid grid-cols-5 gap-px bg-border lg:grid-cols-10">{stats.map((stat)=><div key={stat.digit} className={`bg-panel p-2 transition-colors ${stat.digit===recentDigit?"ring-1 ring-inset ring-primary bg-primary/5":""}`}><div className="flex items-start justify-between"><span className="font-mono text-lg font-semibold">{stat.digit}</span>{stat.trend>0?<TrendingUp className="size-3 text-positive"/>:stat.trend<0?<TrendingDown className="size-3 text-negative"/>:<Minus className="size-3 text-muted-foreground"/>}</div><div className="mt-1 font-mono text-xs font-medium">{stat.percentage.toFixed(1)}%</div><div className="mt-2 h-1 bg-muted"><div className="h-full bg-primary transition-all duration-500" style={{width:`${Math.min(100,stat.percentage*5)}%`}}/></div><div className="mt-1 flex justify-between text-[9px] text-muted-foreground"><span>{stat.count}×</span><span>{stat.lastSeen===0?"now":`${stat.lastSeen} ago`}</span></div></div>)}</div><div className="grid grid-cols-2 gap-px border-t border-border bg-border sm:grid-cols-4 lg:grid-cols-8"><Metric label="Even" value={`${even.toFixed(1)}%`}/><Metric label="Odd" value={`${(100-even).toFixed(1)}%`}/><Metric label="Hot digits" value={`${sorted[0]?.digit}, ${sorted[1]?.digit}`}/><Metric label="Cold digits" value={`${sorted[8]?.digit}, ${sorted[9]?.digit}`}/><Metric label="Most recent" value={String(recentDigit)} accent/><Metric label="Current streak" value={`${streakDigit} × 1`}/><Metric label="Parity" value={sentinel.parity}/><Metric label="Pressure" value={`${sentinel.pressure}%`}/></div><button onClick={onPressure} className="flex w-full items-center justify-between border-t border-border px-3 py-2 text-xs hover:bg-accent"><span className="label">Digit pressure</span>{pressureOpen?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</button>{pressureOpen&&<div className="grid grid-cols-5 gap-px border-t border-border bg-border lg:grid-cols-10">{stats.map(s=><div key={s.digit} className="flex items-center justify-center gap-2 bg-surface py-2 font-mono text-xs"><span>{s.digit}</span><span className={s.trend>0?"text-positive":s.trend<0?"text-negative":"text-muted-foreground"}>{s.trend===2?"↑↑":s.trend===1?"↑":s.trend===-2?"↓↓":s.trend===-1?"↓":"→"}</span></div>)}</div>}</section>;
}
function Metric({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="bg-surface px-3 py-2"><div className="text-[9px] uppercase text-muted-foreground">{label}</div><div className={`mt-0.5 font-mono text-xs font-semibold ${accent?"text-primary":""}`}>{value}</div></div>}
