import { ChevronLeft, ChevronRight, Search, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useMemo, useState } from "react";
import type { Market } from "../types";

export function MarketFinder({ markets, collapsed, onToggle, onSelect }: { markets: Market[]; collapsed: boolean; onToggle: () => void; onSelect: (market: Market) => void }) {
 const [query, setQuery] = useState(""); const filtered = useMemo(() => markets.filter((m) => m.name.toLowerCase().includes(query.toLowerCase())), [markets, query]);
 if (collapsed) return <aside className="hidden w-12 shrink-0 border-r border-border bg-panel lg:flex lg:flex-col lg:items-center lg:py-3"><Button size="icon" variant="ghost" onClick={onToggle} aria-label="Open market finder"><ChevronRight/></Button><span className="mt-8 [writing-mode:vertical-rl] text-[10px] uppercase tracking-[0.2em] text-muted-foreground">Markets</span></aside>;
 const categories = ["Favourites","Volatility","Crash/Boom","Jump","Step","Range Break"];
 return <aside className="hidden w-64 shrink-0 overflow-y-auto border-r border-border bg-panel lg:block"><div className="sticky top-0 z-10 border-b border-border bg-panel p-3"><div className="mb-3 flex items-center justify-between"><span className="label">Market finder</span><Button size="icon" variant="ghost" onClick={onToggle} aria-label="Collapse market finder"><ChevronLeft/></Button></div><div className="relative"><Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search derived markets" className="pl-8"/></div></div><div className="p-2">{categories.map((category) => { const items = filtered.filter((m) => category === "Favourites" ? m.favourite : m.category === category); if (!items.length) return null; return <section key={category} className="mb-4"><div className="px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">{category}</div>{items.map((market) => <button key={market.id} onClick={() => onSelect(market)} className="flex w-full items-center gap-2 border-l-2 border-transparent px-2 py-2.5 text-left transition-colors hover:border-primary hover:bg-accent"><Star className={`size-3 ${market.favourite ? "fill-warning text-warning" : "text-muted-foreground"}`}/><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium">{market.name}</div><div className="font-mono text-[10px] text-muted-foreground">{market.basePrice.toFixed(market.decimals)}</div></div><span className="text-[9px] text-positive">LIVE</span></button>)}</section>})}</div></aside>;
}
